# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sinatra", "~> 2.0"
gem "rbwebview", git: 'https://github.com/kevinwong197/webview.git'
gem "ocra", "~> 1.3"
gem "find_a_port", "~> 1.0"
gem "rake", "~> 12.3"
